version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    - pip install pydoctor
    - | 
      pydoctor \
      --project-version=$READTHEDOCS_GIT_IDENTIFIER \
      --project-url=https://github.com/$GITHUB_REPOSITORY \
      --html-viewsource-base=$READTHEDOCS_GIT_CLONE_URL/tree/$READTHEDOCS_GIT_COMMIT_HASH \
      --html-base-url=$READTHEDOCS_CANONICAL_URL \
      --html-output $READTHEDOCS_OUTPUT/html/ \
      ./libstatic
