name: docs
on: 
  push:
    branches: 
      - main
    tags: 
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

    permissions: 
      contents: write

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip setuptools wheel
        # version of pydoctor that handles re-exports the way I want.
        python -m pip install git+https://github.com/twisted/pydoctor.git@2807558653743b35b0279ac553cdf92d0253febd

    - name: Generate docs
      run: |
        # Run pydoctor build
        pydoctor -W

    - name: Push docs to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apidocs
        commit_message: "Generate docs"
